### PR TITLE
Add support for default cluster network and network readiness

### PR DESCRIPTION
**Pull request by satyaranjanp**
Test report:
[test-report.docx](https://github.com/Huawei-PaaS/CNI-Genie/files/2717885/test-report.docx)

### CODE REVIEW

**Comment by sushanthakumar** [comment]
@satyaranjanp , Can u update test report with some cases like, 1)networkattachment also asking for etho which is not possible to provide 2) Creating pod when default network no ready

**Comment by m1093782566** [comment]
@sushanthakumar 

Shall we cut a new release now?

**Comment by sushanthakumar** [comment]
Hi Dujun, We are currently working on adding some documentation for this feature and also below activity with which we can logically cut a release this week
https://github.com/Huawei-PaaS/CNI-Genie/issues/154

**Comment by m1093782566** [comment]
Sounds a great plan! Thanks!

**Pull request merged**
