### PR TITLE
Add support for sr-iov plugin

### PR DESCRIPTION
**Pull request by satyaranjanp**

### CODE REVIEW

**Comment by kshafiee** [comment]
@jellonek would be great if you can provide feedback on this PR, thx!

**Comment by jellonek** [comment]
As for code - LGTM, but tests now will be failing, because this PR adds new one based on additional binary, but https://github.com/Huawei-PaaS/CNI-Genie/blob/master/plugins_install.sh was not updated to install this binary for sriov plugin.

So IMO this PR needs an update.

BTW. This test can work only on specific hardware, so maybe it should be marked in some way as optional, because on non usual dev machines without sriov support - it will be constantly failing.

**Comment by satyaranjanp** [comment]
Thanks for your review Jellonek.

As you mentioned, sr-iov has specific hardware dependency, hence can not be a part of plugins_install.sh script. So I have disabled this test case from running automatically (Updated this PR).

However, this test case can be run manually to specifically test sr-iov.

**Comment by kshafiee** [comment]
LGTM

**Pull request merged**
