### PR TITLE
Allow to set default plugin

### PR DESCRIPTION
**Pull request by lukaszo**
Now it's possible to set `default_plugin` option in genie config file. If it's not set it still defaults to `weave`

### CODE REVIEW

**Comment by satyaranjanp** [comment]
We will review the changes and update you.

**Comment by sushanthakumar** [comment]
This is some feature we also wanted to support and mechanism is fine
Have below few points
1. Can we call default plugin function from parseCNIAnnotations itself so that it will take care of both add and delete network cases
2. We can add one sample genie conf file with default plugin usage for reference in sampleyamls folder

thanks @lukaszo

**Comment by lukaszo** [comment]
@sushanthakumar I moved calling default plugin.
About part 2, is sampleyamls folder a correct place to add an example file?

**Comment by sushanthakumar** [comment]
@lukaszo, You are right, may be we can have one folder sampleconfigs and place a sample genie config with default usage, in future can be used for any other new extensions

**Comment by lukaszo** [comment]
@sushanthakumar I added sampleconfigs dir with an example where default_plugin is used

**Comment by lukaszo** [comment]
I've rebased PR

**Comment by sushanthakumar** [comment]
@lukaszo, sure, will review and accept it, thanks

**Comment by kshafiee** [comment]
@lukaszo looks like the build is broken somewhere. Could you please see if  PR #79 is possibly causing this?

**Comment by lukaszo** [comment]
@kshafiee fixed, my vim messed up something on write :/

**Comment by kshafiee** [comment]
LGTM

**Comment by sushanthakumar** [comment]
LGTM

**Pull request merged**
