### PR TITLE
CNI panic issue fix

### PR DESCRIPTION
**Pull request by sushanthakumar**
Description: Panic issue happening due to nil result is field
Test Report:
[test-report.docx](https://github.com/Huawei-PaaS/CNI-Genie/files/1614049/test-report.docx)

### CODE REVIEW

**Comment by satyaranjanp** [comment]
LGTM

**Comment by kshafiee** [comment]
@sushanthakumar for some reason I could not open the .doc file above:
screen shot 2018-01-21 at 4 42 40 pm

**Comment by kumarshetty** [comment]
Attached the test report again, pls have a check whether you can open it
[test-report.docx](https://github.com/Huawei-PaaS/CNI-Genie/files/1650904/test-report.docx)

**Comment by sushanthakumar** [comment]
Attached the test report again, pls have a look whether u can open it
[test-report.docx](https://github.com/Huawei-PaaS/CNI-Genie/files/1650907/test-report.docx)

**Pull request merged**
