### PR TITLE
Documentation for default plugin support

### PR DESCRIPTION
**Pull request by sushanthakumar**
PR to add documentation for default plugin support

### CODE REVIEW

**Comment by sushanthakumar** [comment]
Pls review this PR
@lukaszo , @gopinatht , pls have a look if it is clear/covers the feature well

**Comment by sushanthakumar** [comment]
Below link can be used for review
https://github.com/sushanthakumar/CNI-Genie/blob/default-plugin-doc/docs/default-plugin/README.md

**Comment by kshafiee** [comment]
LGTM

**Comment by satyaranjanp** [comment]
LGTM

**Comment by lukaszo** [comment]
Sorry for a late answer. I've just came back from vacation. The change looks good :)

**Pull request merged**
