### PR TITLE
Use raw data from config file as stdin for plugin

### PR DESCRIPTION
**Pull request by lukaszo**
Some plugins have extra parameters in config which will be lost during
parsing/marshaling.
Opencontrail cni plugin is such an example

### CODE REVIEW

**Comment by lukaszo** [comment]
It makes #51 obsolete

**Comment by kshafiee** [comment]
@sushanthakumar @satyaranjanp

**Comment by sushanthakumar** [comment]
@lukaszo, Will look into your modifications and update u, thanks

**Comment by satyaranjanp** [comment]
The method looks good.
However the following scenarios also should be taken care of:
1. Where the conf file contains an array of confs:
E.g. for the latest flannel, it creates 10-flannel.conflist which contains an array of configurations. Directly passing the whole conf to cni results in error.
In this case we have to parse the elements of the array separately and handle them.

2. In case of custom-user input, we have to modify the information that we get from the conf file before sending it to cni.
E.g. In case the user wants a custom subnet, then before sending to cni, we need to parse the conf file data and replace the default subnet with the user requested subnet.

May be these points need some more discussion.

**Comment by lukaszo** [comment]
@satyaranjanp currently CNI-Genie doesn't support conflists. Do you have plans to add it?

**Comment by sushanthakumar** [comment]
@lukaszo , we too have noticed and discussed on this. Currently not supported, need to do. If u have any update on this, do let us know, thanks

**Comment by lukaszo** [comment]
@sushanthakumar I think I should be able to add support for conflist. I will also update this PR

**Comment by sushanthakumar** [comment]
@lukaszo , yes , you can go ahead

**Comment by lukaszo** [comment]
I'm closing this one in favor of #73

btw @sushanthakumar is part 2(custom user input) somewhere implemented or is it just a plan?

**Comment by sushanthakumar** [comment]
@lukaszo , part 2, we are analysing currently and will come up with mechanism soon, will update u

**Pull request closed without merging**
