### PR TITLE
Make the error messages more appropriate as per the error scenarios

### PR DESCRIPTION
**Pull request by satyaranjanp**
This PR also solves the panic issue which was caused by nil result.

### CODE REVIEW

**Comment by satyaranjanp** [comment]
This PR addresses issue https://github.com/Huawei-PaaS/CNI-Genie/issues/94

**Comment by satyaranjanp** [comment]
Test Report:

**Comment by kshafiee** [comment]
My only concern is that since we are using "CNI Genie" in the messages, it'd be difficult to differentiate the Errors generated by cni-genie from Errors generated by other plugins:
`tail -f /var/log/syslog | grep 'CNI'` in https://github.com/Huawei-PaaS/CNI-Genie/blob/master/docs/GettingStarted.md#genie-logs

**Comment by satyaranjanp** [comment]
@kshafiee,
The newly added/modified error messages are returned to the calling function and in the calling function, we are already printing the error with the prefix 'CNI Genie'. So I have not added the 'CNI Genie' prefix in these error messages to avoid printing it twice in the same message.

**Comment by sushanthakumar** [comment]
LGTM

**Pull request merged**
