### PR TITLE
Add support for SRIOV cni plugin

### PR DESCRIPTION
**Pull request by michalskalski**
SRIOV cni plugin requires extra parameters, especially IF0 for pointing
NIC used for creation of VFs.

Related to #39

### CODE REVIEW

**Comment by kshafiee** [comment]
@michalskalski we started testing this PR, we will provide feedback shortly

**Comment by jellonek** [comment]
Changes in https://github.com/Mirantis/CNI-Genie/commit/21e44ddaf6473fe5b5762c14bff5e88a5af17408 (which will be hopefully upstreamed today) will allow to do that in more universal way, so it will be not connected only to intel fork of sr-iov (which in fact looks like abandoned, it's only contributor is responding on original one and not on his fork).

**Comment by kshafiee** [comment]
@jellonek Thanks for providing the link!

**Comment by kshafiee** [comment]
@satyaranjanp please take a look at the code and submit a review!

**Comment by sushanthakumar** [comment]
This is handled by below PR, so this PR can be closed
https://github.com/Huawei-PaaS/CNI-Genie/pull/75

**Pull request closed without merging**
