### PR TITLE
Cluster role update for patch operation

### PR DESCRIPTION
**Pull request by sushanthakumar**
Patch was not working since there was no permission for patch operation in cluster role. So multi ip preference was not getting updated in pod
image

Updated genie.yaml file to add  permission for patch operation

Test report: 
[test-report.docx](https://github.com/Huawei-PaaS/CNI-Genie/files/1597383/test-report.docx)

### CODE REVIEW

**Comment by kshafiee** [comment]
LGTM

**Comment by lukaszo** [comment]
Ah, I didn't test my patch with RBAC. Sorry for that.

**Comment by sushanthakumar** [comment]
Added test case to verify multiip-preference case and updated the test report for same

**Comment by satyaranjanp** [comment]
LGTM

**Pull request merged**
